### ISSUE TITLE
less variable parsing fails in import statements

### ISSUE THREAD

**Issue by micgro42** [splitbrain/dokuwiki#2260]
It seems that the new less compiler has another regression, in that the evaluation of variables doesn't work in `@import` statements.

Minimal failing example:

```
.iw_go::after {
    content: "@{ini_assetbase}";
}

@import "@{ini_assetbase}/css/bootstrap.css";
```

The parsing breaks down at the import statement with the error message:
```
A fatal error occured during compilation of the CSS files. If you recently installed a new plugin or template it might be broken and you should try disabling it again. [variable @ini_assetbase is undefined: failed at `@import "/dokuwiki/lib/tpl/foobar/@{ini_assetbase}/css/bootstrap.css";` in /lib/tpl/foobar/css/assets.less at line 9]
```
If I remove the `@import` statement, then the `.iw_go::after` rule evaluates as expected and writes the content of @ini_assetbase into the pseudo-element.

**Comment by splitbrain** [comment]
A git bisect tells me that MarcusSchwarz/lesserphp@011afcca8e6f1000a6e789921ba805fa578271a3 is the first bad commit.

**Comment by phy25** [comment]
Since https://github.com/MarcusSchwarz/lesserphp has fixed this and published v0.5.2, this can be upgraded from upstream now.

**Comment by splitbrain** [comment]
we're already using 0.5.4 so I guess this can be closed
