### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/dokuwiki#2301]
The nightly builds are currently failing. It seems like there's something not working in the upcoming PHP 7.3 release.

**Comment by phy25** [comment]
A hint: Don't know where in PHP's regex part changed (version released at about Dec 2017), causing the failure.

**Comment by AmritasyaPutra** [comment]
lexer.php is not PHP 7.3 ready.  I get "preg_match(): Compilation failed". I moved back to PHP 5.6 and repopulated cache then moved into 7.3. Rest of the code seems to be 7.3 ready.

**Comment by phy25** [comment]
@AmritasyaPutra May we know which DokuWiki version you are using? It should have been fixed.

**Comment by AmritasyaPutra** [comment]
Hi phy25 the version that I am using is “Frusterick Manners”. I know it is old, but this particular file has got no substantial update since then. I narrowed down the breakage from php 7.2 to php 7.3. I guess it is related to pcre2-migration#backward_incompatible_changes in context of preg_match_all() call with a large regex in lexer.php. I don't have the bandwidth to test with latest build.

**Comment by splitbrain** [comment]
Current DokuWiki works fine with 7.3

**Comment by phy25** [comment]
According to https://www.dokuwiki.org/changes, Hotfix 2017-02-19f "Frusterick Manners" should have "fixed PHP 7.3 compatibility 2622 and ACL check". You may check what specific version number you have on admin dashboard (should be at the bottom), or by visiting `?do=check` with superuser logged in.

If you don't want to install patch upgrade, you can definitely try replacing the lexer.php with the latest one but you have to take you own risk.

**Comment by AmritasyaPutra** [comment]
It breaks in preg_match() call in split() in lexer.php. Which means the regex to preg_match_all() call in _getCompoundedRegex() itself is right but one of the resulting regex which is eventually used by preg_match() is not pcre2 compatible but it is valid pcre1 regex. Can this be because I am using bootstrap3 template? It isn't pcre2 ready.

**Comment by phy25** [comment]
@AmritasyaPutra I have no idea. BTW if you are still having issues, are you using the latest patch version? (the alphabet after the version date matters.)

**Comment by AmritasyaPutra** [comment]
You may be right, I am on 2017-02-19e "Frusterick Manners". I will update if it is reproduced after I move to latest stable release.

**Comment by AmritasyaPutra** [comment]
I upgraded to 2018-04-22b "Greebo" after much struggle. It helped the issue is gone from Dokuwiki code. But as feared bootstrap3 template is not php 7.3 ready. So I continue to run on php 7.2.

**Comment by phy25** [comment]
*Just a FYI for future travelers here: "Frusterick Manners" `2017-02-19e` can be upgraded to `2017-02-19f` without the need of upgrading to a major next version.*

@AmritasyaPutra We cannot say anything about `bootstrap3` since it's not maintained as core templates, but you may want to check out https://github.com/LotarProject/dokuwiki-template-bootstrap3

**Comment by AmritasyaPutra** [comment]
Thank you. Yes, I had put some comments on that project, I even saw that he has made appropriate changes in dev branch for php 7.3 compatibility. I don't know what happened but my question about next release date or suitability of directly using dev branch was deleted.

**Comment by qris** [comment]
> _Just a FYI for future travelers here: "Frusterick Manners" `2017-02-19e` can be upgraded to `2017-02-19f` without the need of upgrading to a major next version._ Edit: However, [5a16501](https://github.com/dokuwiki/dokuwiki/commit/5a1650175ab98472a3435716949986f9698eef89) is not included.

Unfortunately it's not in 2017-02-19g (the latest at this time) either.

**Comment by Klap-in** [comment]
Better upgrade your wiki to the latest versions, it is not doable for us to keep supporting these older versions.

**Comment by Michaelsy** [comment]
> it is not doable for us to keep supporting these older versions.

Of course, version 2017-02-19g will continue to be supported. Many updates have been released since then, the latest of which is 2024-02-06b "Kaos"...

\- Michael Sy.
